version: '3'
services:
  cgi:
    build: ./cgi/go
    ports:
      - "80:80"

  jsp:
    image: tomcat:9.0.13-jre11-slim
    volumes:
      - ./jsp:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"

  cgi-python:
    build: ./cgi/python
    ports:
      - "81:80"